### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by javelin-ken** [javelin-ken/furima-34869#10]
#URL
https://furima-34869.herokuapp.com/

#Basic認証のIDとパスワード
ID: free819
Password:  furima34869

#出品者用のメールアドレスパスワード
email:  kensei@kensei
password: kensei111

#購入者用のメールアドレスパスワード
email:  yakiniku@yakiniku
password:  yakiniku111

**Comment by snkw-works** [comment]
@javelin-ken さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **商品出品ページ・商品情報編集ページにて、エラーハンドリングの際、1つのエラーに対して同じエラーメッセージが重複して表示されないよう修正しましょう**
現状、「Price can't be blank」というエラーメッセージが重複して表示されている状態です。
<img width="264" alt="スクリーンショット_2021-04-06_16_53_32" src="https://user-images.githubusercontent.com/54050089/113678111-3e3adc00-96f9-11eb-859b-34541e41b0a9.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by javelin-ken** [comment]
修正しました！

**Comment by snkw-works** [comment]
@javelin-ken さん、ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/113683429-28301a00-96ff-11eb-9c4a-e70515692579.png)
